### ISSUE TITLE
About section on users

### ISSUE THREAD

**Issue by edgib102** [Code2Gether-Discord/Code2Gether-Discord-Bot#15]
Used for the other functions on the bot as well as personal uses. Would link GitHub username and about me

command like c!finduser edgib102 - returns discord username

**Comment by nickmartin1ee7** [comment]
Ooh, yeah! That's good.
I can see people using a command to link their github name and other people using a command to see what it is.

**Comment by nickmartin1ee7** [comment]
A User Story will be opened on this. This issue will be closed.
