### ISSUE TITLE
[BUG] Technical issue where Async code is not programmed properly in C#

### ISSUE THREAD

**Issue by DonSagiv** [Code2Gether-Discord/Code2Gether-Discord-Bot#16]
**Describe the bug**
Some of the code is not making proper use of the Async methods.

**Expected behavior**
The "async" keyword should be properly used for code blocs that have asynchronous methods.

**Comment by RupertAvery** [comment]
Please give all known code locations where this occurs so it can be addressed.

**Comment by nickmartin1ee7** [comment]
PingLogic.cs - Line 46
`temporaryMessage.DeleteAsync();`
