### ISSUE TITLE
[User Story] As a developer, I want store my project and user data persistently (Discord-bot back-end)

### ISSUE THREAD

**Issue by DonSagiv** [Code2Gether-Discord/Code2Gether-Discord-Bot#20]
[Create/Update]
**Given** a project/user (or its details) is created/updated on the Discord bot.
**When** the project/user is being saved.
**Then** serialize the data and save it onto an SQL-based database.

[Read]
**Given** the details of a project/user is exists on an SQL-based database.
**When** the project/user is being requested by the Discord bot.
**Then** de-serialize the data on the database, and return return it to the bot.

The details of how this is done is not yet fully known. Tentatively, a Web-API attached to an SQLite database will be used. The front-end (bot) will make a WebAPI request to the back-end (SQLite) that's on a server. The server will likely be a Docker container.

**Comment by nickmartin1ee7** [comment]
Business rules for database regarding project command defined at #31

**Comment by nickmartin1ee7** [comment]
**Given** a project exists
**When** a GET request is made to Project endpoint with a given Project Id
**Then** return the serialized form of a project, which contains a collection of each Discord member's (ie. their Discord User snowflake)
