### ISSUE TITLE
[BUG] Joining an existing project results in a new channel even though one already exists

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/Code2Gether-Discord-Bot#60]
**Describe the bug**
Multiple channels being created when a user does the c!join project command

**To Reproduce**
1. c!join a project that has atleast 2 members
3. A new channel has been created even though one exists

**Expected behavior**
The user should join the existing channel

**Comment by nickmartin1ee7** [comment]
This has to do the with transition to active project being run each time a new user joins.

The logic should behave as the following:
1. If the project name channel doesn't exist, add it under the category containing "projects"
2. If the role with the project name doesn't exist, create it
2. For each project member, add the project role if they don't have it

**Comment by nickmartin1ee7** [comment]
Command will be completely refactored with new GitHub API integration.
Closing as Project-related commands using Custom WebAPI will be replaced with GitHub API.
