### ISSUE TITLE
[BUG] c!help command results in incomplete usage for c!github join-org

### ISSUE THREAD

**Issue by nickmartin1ee7** [Code2Gether-Discord/Code2Gether-Discord-Bot#63]
**Describe the bug**
The bug is essentially a missing "]" character from the github join-org's help text. This is likely a typo where in the attribute description for the command.

**To Reproduce**
1. Send c!help
2. See missing "]" in output

**Expected behavior**
"c!github join-org (github join-org; github jo; github join-organization; ) - Join the GitHub Organization at https://github.com/Code2Gether-Discord. Usage: github join-org [email**]**"

**Screenshots**
![image](https://user-images.githubusercontent.com/58752614/108232527-df9dac80-7110-11eb-8f3c-3e19c6ae1dcd.png)

**Additional context**
This should be a typo in the github join-org module class

**Comment by sumitk63** [comment]
Hey Nick i would like to fix this typo, can i start working on this?

**Comment by nickmartin1ee7** [comment]
> Hey Nick i would like to fix this typo, can i start working on this?

Yeah! Go for it. I'll assign this to you
